name = "braille-stl-generator"
compatibility_date = "2024-09-21"
pages_build_output_dir = "dist"

# Build configuration for Pages
[build]
command = "npm run build"

[build.environment_variables]
NODE_VERSION = "20"

# Cloudflare Pages settings
[site]
bucket = "dist"

# Custom domains (to be configured)
# [[env.production.route]]
# pattern = "braille-stl.your-domain.com"
# zone_name = "your-domain.com"

# Worker routes (if needed for future API endpoints)
# [[env.production.routes]]
# pattern = "braille-stl.your-domain.com/api/*"
# script = "api-worker"

# Analytics (optional)
[analytics]
enabled = true

# Security settings
[security]
headers = true  # Use cloudflare/_headers file

# Performance settings
[performance]
minify = true
bundle = true
